[versions]
jacoco = "0.8.7"
kotlin = "1.8.22"
okio = "3.3.0"

[libraries]
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "3.14.3" }
kotlinx-coroutines-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version = "1.7.1" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.5.1" }
okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-js = { module = "com.squareup.okio:okio-js", version.ref = "okio" }

[plugins]
binary-compatibility-validator = { id = "binary-compatibility-validator", version = "0.13.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.20" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.15.0" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.25.3" }
