[versions]
jacoco = "0.8.7"
kotlin = "2.0.21"
okio = "3.9.1"

[libraries]
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "3.18.2" }
kotlinx-coroutines-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version = "1.9.0" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.7.3" }
okio-core = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-js = { module = "com.squareup.okio:okio-js", version.ref = "okio" }

[plugins]
api = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.17.0" }
dokka = { id = "org.jetbrains.dokka", version = "2.0.0" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.0.1" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.30.0" }
