[versions]
kotlin = "1.6.0"
okio = "3.0.0-alpha.6"
jacoco = "0.8.7"

[libraries]
kotlinx-coroutines-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version = "1.4.2" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.0.1" }
okio-multiplatform = { module = "com.squareup.okio:okio-multiplatform", version.ref = "okio" }
okio-js = { module = "com.squareup.okio:okio-js", version.ref = "okio" }
mockk = { module = "io.mockk:mockk", version = "1.10.0" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "3.4" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "3.2.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.18.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.4.32" }
binary-compatibility-validator = { id = "binary-compatibility-validator", version = "0.8.0" }
