name: GitHub Pages
on:
  push:
    branches:
      - main

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-gh-pages-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gh-pages-
            ${{ runner.os }}-

      - run: ./gradlew assembleGitHubPages

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/gh-pages
