name: GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true

      - run: ./gradlew assembleGitHubPages
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/gh-pages
