name: Publish
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-publish-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-publish-
            ${{ runner.os }}-

      - run: ./gradlew check
      - run: >-
          ./gradlew
          -PVERSION_NAME="${GITHUB_REF/refs\/tags\//}"
          -PsigningInMemoryKey="${{ secrets.SIGNING_KEY }}"
          -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_PASSWORD }}"
          -PmavenCentralUsername="${{ secrets.OSS_SONATYPE_NEXUS_USERNAME }}"
          -PmavenCentralPassword="${{ secrets.OSS_SONATYPE_NEXUS_PASSWORD }}"
          publish

      - run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
