name: Publish
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: gradle/actions/setup-gradle@v3

      - run: ./gradlew check
      - run: >-
          ./gradlew
          -PVERSION_NAME="${GITHUB_REF/refs\/tags\//}"
          -PsigningInMemoryKey="${{ secrets.SIGNING_KEY }}"
          -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_PASSWORD }}"
          -PmavenCentralUsername="${{ secrets.OSS_SONATYPE_NEXUS_USERNAME }}"
          -PmavenCentralPassword="${{ secrets.OSS_SONATYPE_NEXUS_PASSWORD }}"
          publish
