name: Validate Maven Signing
on:
  push:
    branches:
      - main

jobs:
  signing:
    if: github.repository_owner == 'JuulLabs'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/wrapper-validation-action@v3
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      - run: >
          ./gradlew
          -PsigningInMemoryKey="${{ secrets.SIGNING_KEY }}"
          -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_PASSWORD }}"
          publishToMavenLocal
