name: Snapshot
on:
  push:
    branches:
      - main

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  snapshot:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt-hotspot"
          java-version: "11.0.11+9"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-snapshot-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-snapshot-
            ${{ runner.os }}-

      - run: ./gradlew check
      - run: ./gradlew --no-parallel -PVERSION_NAME=main-SNAPSHOT uploadArchives
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.OSS_SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.OSS_SONATYPE_NEXUS_PASSWORD }}

      - run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
